version: "2"

services:
  redis:
    image: "bitnami/redis:7.0"
    restart: always
    environment:
      - REDIS_PASSWORD=123456
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 1024mb
    ports:
      - "16379:6379"